# Generated by Django 4.2.16 on 2026-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('tipo_proyecto', models.CharField(choices=[('LP', 'Landing Page'), ('SW', 'Sitio Web'), ('SM', 'Sistema a Medida'), ('PM', 'Consultoría PM'), ('OT', 'Otro')], max_length=2)),
                ('presupuesto', models.CharField(blank=True, max_length=50)),
                ('mensaje', models.TextField()),
                ('fuente', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
    ]
