# Generated by Django 4.2.16 on 2026-06-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('icono', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('cliente', models.CharField(max_length=80)),
                ('imagen_principal', models.ImageField(upload_to='proyectos/')),
                ('descripcion_corta', models.TextField(max_length=200)),
                ('descripcion_larga', models.TextField()),
                ('reto', models.TextField()),
                ('solucion', models.TextField()),
                ('resultados', models.TextField(blank=True)),
                ('url_sitio', models.URLField(blank=True)),
                ('testimonio_cliente', models.TextField(blank=True)),
                ('testimonio_nombre', models.CharField(blank=True, max_length=80)),
                ('testimonio_cargo', models.CharField(blank=True, max_length=80)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.categoria')),
                ('tecnologias', models.ManyToManyField(to='portfolio.tecnologia')),
            ],
        ),
    ]
