# Generated by Django 4.2.16 on 2026-06-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion_larga',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen_principal',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='reto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='solucion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tecnologias',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='testimonio_cargo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='testimonio_cliente',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='testimonio_nombre',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='url_sitio',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_corta',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Tecnologia',
        ),
    ]
